services:
  backend:
   image: zono32/calculadora-backend:v0.1
   container_name: backend
   ports:
     - 8000:8000

  frontend:
   image: zono32/calculadora-frontend:v0.1
   container_name: frontend
   depends_on: 
    - backend
   ports:
    - 80:80