# Utilizar una imagen base oficial de Python
FROM python:3.11-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo de dependencias (requirements.txt)
COPY requirements.txt .

# Instalar las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto que FastAPI utilizará
EXPOSE 8000

# Ejecutar la aplicación FastAPI desde el archivo main.py
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000"]

# fastapi dev main.py --port 8001