# Usar una imagen oficial de Nginx
FROM nginx:alpine

# Copiar los archivos del frontend (HTML, CSS, JS) a la carpeta de Nginx
COPY . /usr/share/nginx/html


# Exponer el puerto en el que Nginx estará sirviendo los archivos
EXPOSE 80